import type { Metadata } from "next";
import { DM_Sans, Poppins } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";
import { LoaderProvider } from "@/context/loader-context";
import { UserProvider } from "@/context/auth-context";
import { Toaster } from "@/components/ui/sonner";
import GlobalLoader from "@/components/common/globalLoader";

const dmSans = DM_Sans({
  variable: "--font-dm",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${poppins.variable} antialiased`}
      >
        <QueryProvider>
          <LoaderProvider>
            <UserProvider>
              <Toaster />
              <GlobalLoader>{children}</GlobalLoader>
            </UserProvider>
          </LoaderProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
